name: Continuous Integration

on:
  push:
    branches:
      - main
      - actions-*
    tags:
      - v*
  pull_request:
    branches-ignore:
      - actions-*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: "ruby"
            label: "latest"
            standardrb: true
            yard: true
          - ruby: "ruby"
            label: "force prepend"
            env:
              HTTP_INSTRUMENTATION_FORCE_PREPEND: "true"
          - ruby: "2.6"
            appraisal: "curb_0.9"
          - ruby: "3.2"
            appraisal: "curb_1.0"
          - ruby: "2.6"
            appraisal: "ethon_0.8"
            frozen_strings: false
          - ruby: "2.6"
            appraisal: "excon_0.19"
            frozen_strings: false
          - ruby: "3.2"
            appraisal: "excon_1.0"
          - ruby: "2.6"
            appraisal: "http_1.0"
            frozen_strings: false
          - ruby: "2.7"
            appraisal: "http_2.0"
          - ruby: "2.7"
            appraisal: "http_3.0"
          - ruby: "2.7"
            appraisal: "http_4.0"
          - ruby: "3.1"
            appraisal: "http_5.0"
          - ruby: "4.0"
            appraisal: "http_6.0"
          - ruby: "2.6"
            appraisal: "httpclient_2.7"
            frozen_strings: false
          - ruby: "2.7"
            appraisal: "httpx_0.2"
          - ruby: "3.1"
            appraisal: "httpx_1.0"
          - ruby: "ruby"
            appraisal: "net_http_latest"
          - ruby: "2.6"
            appraisal: "patron_0.5"
          - ruby: "2.6"
            appraisal: "typhoeus_0.7"
          - ruby: "2.7"
            appraisal: "typhoeus_1.3"
          - ruby: "ruby"
            appraisal: "with_webmock"
          - ruby: "ruby"
            appraisal: "with_apms"
          - ruby: "ruby"
            appraisal: "with_open_telemetry"
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev
      - name: Ruby CI
        uses: bdurand/github-actions/ruby-ci@main
        with:
          ruby: ${{ matrix.ruby }}
          appraisal: ${{ matrix.appraisal }}
          bundler: ${{ matrix.bundler }}
          standardrb: ${{ matrix.standardrb }}
          yard: ${{ matrix.yard }}
