name: Continuous Integration

on:
  push:
    branches:
      - main
      - actions-*
    tags:
      - v*
  pull_request:
    branches-ignore:
      - actions-*

env:
  BUNDLE_CLEAN: "true"
  BUNDLE_PATH: vendor/bundle
  BUNDLE_JOBS: 3
  BUNDLE_RETRY: 3

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: "ruby"
            standardrb: true
          - ruby: "2.5"
            appraisal: "curb_0.9"
          - ruby: "2.5"
            appraisal: "ethon_0.8"
          - ruby: "2.5"
            appraisal: "excon_0.19"
          - ruby: "2.5"
            appraisal: "http_1.0"
          - ruby: "2.6"
            appraisal: "http_2.0"
          - ruby: "2.7"
            appraisal: "http_3.0"
          - ruby: "3.0"
            appraisal: "http_4.0"
          - ruby: "3.1"
            appraisal: "http_5.0"
          - ruby: "2.5"
            appraisal: "httpclient_2.7"
          - ruby: "2.5"
            appraisal: "httpx_0.2"
          - ruby: "2.5"
            appraisal: "patron_0.5"
          - ruby: "2.5"
            appraisal: "typhoeus_0.7"
          - ruby: "2.7"
            appraisal: "typhoeus_1.3"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
    - name: Install dependencies
      run: sudo apt-get install libcurl4-openssl-dev
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install libsqlite3-dev
    - name: Setup bundler
      if: matrix.bundler != ''
      run: |
        gem uninstall bundler --all
        gem install bundler --no-document --version ${{ matrix.bundler }}
    - name: Set Appraisal bundle
      if: matrix.appraisal != ''
      run: |
        echo "using gemfile gemfiles/${{ matrix.appraisal }}.gemfile"
        bundle config set gemfile "gemfiles/${{ matrix.appraisal }}.gemfile"
    - name: Install gems
      run: |
        bundle update
    - name: Run Tests
      run: bundle exec rake
    - name: standardrb
      if:   matrix.standardrb == true
      run:  bundle exec rake standard
